import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer>
        <span className="font-sans text-2xl">
          This is a design test by Calin Ennis for&nbsp;
          <a
            href="https://monogram.io/"
            target="_blank"
            rel="noopener noreferrer"
            className="underline decoration-purple-500 text-purple-500"
          >
            Monogram
          </a>
          .
        </span>

        <span>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
};

export default Home;
